services:
  owl.registry.date_provider_filter:
    class: Owl\Shared\Domain\DataProvider\Registry\FilterRegistry
    arguments:
      - 'Owl\Shared\Domain\DataProvider\Filter\FilterInterface'
      - 'data provider filter'

  owl.data_provider.doctrine.filter_factory_builder:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\FilterFactoryBuilder
    arguments:
      - '@owl.registry.date_provider_filter'

  owl.data_provider.doctrine.collection_type_builder:
    class: Owl\Shared\Infrastructure\DataProvider\Orm\Builder\CollectionTypeBuilder
    arguments:
      - '@owl.registry.date_provider_filter'
      # - '@owl.data_provider.doctrine.filter_applicator'

  Owl\Shared\Domain\DataProvider\CollectionDataProviderInterface:
    class: Owl\Shared\Infrastructure\DataProvider\CollectionDataProvider
    arguments:
      - '@owl.data_provider.doctrine.collection_type_builder'

  # owl.data_provider.doctrine.filter_applicator:
  #   class: Owl\Shared\Infrastructure\DataProvider\Orm\Applicator\FilterApplicator


