services:
  _defaults:
    autoconfigure: true
    autowire: true

  Owl\Apps\Api\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # Autowire
  Owl\:
    resource: '../../../src'