<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR2qfyDX\Owl_Apps_Api_ApiKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR2qfyDX/Owl_Apps_Api_ApiKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR2qfyDX.legacy');

    return;
}

if (!\class_exists(Owl_Apps_Api_ApiKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR2qfyDX\Owl_Apps_Api_ApiKernelDevDebugContainer::class, Owl_Apps_Api_ApiKernelDevDebugContainer::class, false);
}

return new \ContainerR2qfyDX\Owl_Apps_Api_ApiKernelDevDebugContainer([
    'container.build_hash' => 'R2qfyDX',
    'container.build_id' => '4c0fa3a3',
    'container.build_time' => 1677515387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR2qfyDX');
