<?php

namespace ContainerR2qfyDX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleRepositoryService extends Owl_Apps_Api_ApiKernelDevDebugContainer
{
    /**
     * Gets the private 'Owl\Article\Infrastructure\Persistence\ArticleRepository' shared autowired service.
     *
     * @return \Owl\Article\Infrastructure\Persistence\ArticleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/var-exporter/LazyGhostTrait.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 6).'/src/Shared/Infrastructure/Persistence/Doctrine/DoctrineRepository.php';
        include_once \dirname(__DIR__, 6).'/src/Article/Domain/Repository/ArticleRepositoryInterface.php';
        include_once \dirname(__DIR__, 6).'/src/Article/Infrastructure/Persistence/ArticleRepository.php';

        return $container->privates['Owl\\Article\\Infrastructure\\Persistence\\ArticleRepository'] = new \Owl\Article\Infrastructure\Persistence\ArticleRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
