<?php

namespace ContainerR2qfyDX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Middleware_ValidationService extends Owl_Apps_Api_ApiKernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.middleware.validation' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\ValidationMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/messenger/Middleware/ValidationMiddleware.php';

        return $container->privates['messenger.middleware.validation'] = new \Symfony\Component\Messenger\Middleware\ValidationMiddleware(($container->privates['validator'] ?? $container->load('getValidatorService')));
    }
}
